package com.example.hits_android.expressionParser

enum class Name (val value: String) {
    RAND("rand()"),
    SPACE("space"),
    NEW_STRING("\n"),
    PLUS("+"),
    MINUS("-"),
    MULTIPLY("*"),
    DIVIDE("/"),
    OR("||"),
    AND("&&"),
    MOD("%"),
    ASSIGN("="),
    COMMA(","),
    COLON(":"),
    SEMICOLON(";"),
    NUMBER("number"),
    VARIABLE("variable"),
    EQUALS("=="),
    NOT_EQUALS("!="),
    L_BRACKET("("),
    R_BRACKET(")"),
    L_SQUARE_BRACKET("["),
    R_SQUARE_BRACKET("]"),
    L_FIG_BRACKET("{"),
    R_FIG_BRACKET("}"),
    GREATER_OR_EQUALS(">="),
    LESS_OR_EQUALS("<="),
    GREATER(">"),
    LESS("<")
}